# Generated by Django 4.1.2 on 2022-10-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participents',
            field=models.ManyToManyField(null=True, to='events.participent'),
        ),
    ]
