# Generated by Django 4.1.2 on 2022-10-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_participents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participent',
            name='extra_data',
            field=models.TextField(null=True),
        ),
    ]
