# Generated by Django 4.1.2 on 2022-10-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_participent_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participents',
            field=models.ManyToManyField(to='events.participent'),
        ),
    ]
