# Generated by Django 4.1.2 on 2022-10-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_member_acadimic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('start', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('members', models.ManyToManyField(to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.member')),
            ],
        ),
    ]
