# Generated by Django 4.1.2 on 2022-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_member_acadimic_year'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target',
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.ManyToManyField(to='accounts.member'),
        ),
    ]
