# Generated by Django 4.1.2 on 2022-10-17 17:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=5)),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, unique=True)),
                ('major', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=1000)),
                ('acadimic_year', models.IntegerField(default=1)),
                ('univ_fac', models.TextField(max_length=200)),
                ('departement', models.CharField(choices=[('ME', 'Men...'), ('WI', 'WI...')], default='ME', max_length=2)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
    ]
