# Generated by Django 4.1.2 on 2022-10-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='full_name',
        ),
        migrations.AddField(
            model_name='member',
            name='facebook_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
