# Generated by Django 4.1.2 on 2022-10-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_member_full_name_member_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_name',
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='12345678', max_length=16),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='newu', max_length=5),
        ),
    ]
