# Generated by Django 4.1.2 on 2022-10-19 16:26

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_member_password_member_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
